// <auto-generated />
using System;
using Biblioteka.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Biblioteka.Migrations
{
    [DbContext(typeof(BibliotekaContext))]
    [Migration("20251114194429_update")]
    partial class update
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.22");

            modelBuilder.Entity("Biblioteka.Models.HistoriaWyszukiwan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataZapisu")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Zapytanie")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("HistoriaWyszukiwan");
                });

            modelBuilder.Entity("Biblioteka.Models.Kategoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Kategorie");
                });

            modelBuilder.Entity("Biblioteka.Models.Ksiazka", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("KategoriaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SpisTresci")
                        .HasColumnType("TEXT");

                    b.Property<string>("autor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("isbn")
                        .HasColumnType("INTEGER");

                    b.Property<string>("stan")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("tag")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("tytul")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KategoriaId");

                    b.ToTable("Ksiazki");
                });

            modelBuilder.Entity("Biblioteka.Models.Rezerwacja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataRezerwacji")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataWygasniecia")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KsiazkaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("KsiazkaId");

                    b.HasIndex("UserId");

                    b.ToTable("Rezerwacje");
                });

            modelBuilder.Entity("Biblioteka.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Rola")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("dataRejestracji")
                        .HasColumnType("TEXT");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("haslo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("iloscWypKsiazek")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Biblioteka.Models.Wypozyczenie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataWypozyczenia")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FaktycznaDataZwrotu")
                        .HasColumnType("TEXT");

                    b.Property<int>("KsiazkaId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OczekiwanaDataZwrotu")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Przedluzono")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("KsiazkaId");

                    b.HasIndex("UserId");

                    b.ToTable("Wypozyczenia");
                });

            modelBuilder.Entity("Biblioteka.Models.HistoriaWyszukiwan", b =>
                {
                    b.HasOne("Biblioteka.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Biblioteka.Models.Kategoria", b =>
                {
                    b.HasOne("Biblioteka.Models.Kategoria", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Biblioteka.Models.Ksiazka", b =>
                {
                    b.HasOne("Biblioteka.Models.Kategoria", "Kategoria")
                        .WithMany("Ksiazki")
                        .HasForeignKey("KategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kategoria");
                });

            modelBuilder.Entity("Biblioteka.Models.Rezerwacja", b =>
                {
                    b.HasOne("Biblioteka.Models.Ksiazka", "Ksiazka")
                        .WithMany()
                        .HasForeignKey("KsiazkaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Biblioteka.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ksiazka");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Biblioteka.Models.Wypozyczenie", b =>
                {
                    b.HasOne("Biblioteka.Models.Ksiazka", "Ksiazka")
                        .WithMany()
                        .HasForeignKey("KsiazkaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Biblioteka.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ksiazka");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Biblioteka.Models.Kategoria", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Ksiazki");
                });
#pragma warning restore 612, 618
        }
    }
}
